-- MySQL Script generated by MySQL Workbench
-- ter 20 jun 2023 10:59:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(45) NOT NULL,
  `sobrenome_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `data_nascimento_user` DATE NOT NULL,
  `senha_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `nome_local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_locais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_peixe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_peixe` (
  `id_peixe` INT NOT NULL AUTO_INCREMENT,
  `nome_peixe` VARCHAR(45) NOT NULL,
  `comprimento_peixe` FLOAT NOT NULL,
  `peso_peixe` FLOAT NOT NULL,
  PRIMARY KEY (`id_peixe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pesca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pesca` (
  `id_pesca` INT NOT NULL AUTO_INCREMENT,
  `id_local` INT NOT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  `tb_peixe_id_peixe` INT NOT NULL,
  `data_pesca` DATE NOT NULL,
  PRIMARY KEY (`id_pesca`),
  INDEX `fk_tb_pesca_tb_local_idx` (`id_local` ASC) VISIBLE,
  INDEX `fk_tb_pesca_tb_usuario1_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_pesca_tb_peixe1_idx` (`tb_peixe_id_peixe` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pesca_tb_local`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`tb_local` (`id_locais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesca_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `mydb`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesca_tb_peixe1`
    FOREIGN KEY (`tb_peixe_id_peixe`)
    REFERENCES `mydb`.`tb_peixe` (`id_peixe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `tipo_item` CHAR NOT NULL,
  `peso_item` FLOAT NOT NULL,
  `comprimento_item` FLOAT NOT NULL,
  PRIMARY KEY (`tb_item`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
